"""
Generated by acem-script-builder.

Project: models
Target: acem-feed-one
Prod branch: main @ 1111111111111111111111111111111111111111
Dev branch: dev @ 2222222222222222222222222222222222222222

This file is generated. Do not edit by hand.
"""

import traceback


def log_event(stage, scope, message):
    print(f"[{stage}] {scope}: {message}")


def output_prod(stage_name, status, payload=None):
    print(f"[PROD OUTPUT] {stage_name} status={status}")
    if payload is not None:
        print(payload)


def output_test(stage_name, status, payload=None):
    print(f"[DEV OUTPUT] {stage_name} status={status}")
    if payload is not None:
        print(payload)


def _build_namespace(metadata):
    return {
        "__name__": "__generated_stage__",
        "__file__": metadata["original_file"],
        "STAGE_METADATA": metadata,
        "output_prod": output_prod,
        "output_test": output_test,
        "log_event": log_event,
    }


def execute_stage(stage_mode, stage_name, stage_record):
    metadata = stage_record["metadata"]
    source = stage_record["source"]
    namespace = _build_namespace(metadata)
    try:
        log_event(stage_mode, stage_name, f"starting {metadata}")
        exec(
            compile(
                source,
                metadata["original_file"],
                "exec",
            ),
            namespace,
            namespace,
        )
        payload = {
            "metadata": metadata,
            "symbols": sorted(namespace.keys()),
        }
        if stage_mode == "prod":
            output_prod(stage_name, "success", payload)
        else:
            output_test(stage_name, "success", payload)
        return payload
    except Exception as exc:
        log_event(stage_mode, stage_name, f"failed with {exc}")
        traceback.print_exc()
        return None


STAGE_SOURCES = {
    "data_fetcher": {
        "prod": {
            "source": "def fetch():\n    return {'source': 'prod'}\n",
            "metadata": {
                "source_project": "models",
                "source_branch": "main",
                "source_target": "acem-feed-one",
                "original_file": "Models/Feeds/acem-feed-one/data_fetcher.py",
                "commit_sha": "1111111111111111111111111111111111111111",
            },
        },
        "dev": {
            "source": "def fetch():\n    return {'source': 'dev'}\n",
            "metadata": {
                "source_project": "models",
                "source_branch": "dev",
                "source_target": "acem-feed-one",
                "original_file": "Models/Feeds/acem-feed-one/data_fetcher.py",
                "commit_sha": "2222222222222222222222222222222222222222",
            },
        },
    },
    "processing": {
        "prod": {
            "source": "def process(data):\n    return {'processed': 'prod', 'data': data}\n",
            "metadata": {
                "source_project": "models",
                "source_branch": "main",
                "source_target": "acem-feed-one",
                "original_file": "Models/Feeds/acem-feed-one/processing.py",
                "commit_sha": "1111111111111111111111111111111111111111",
            },
        },
        "dev": {
            "source": "def process(data):\n    return {'processed': 'dev', 'data': data}\n",
            "metadata": {
                "source_project": "models",
                "source_branch": "dev",
                "source_target": "acem-feed-one",
                "original_file": "Models/Feeds/acem-feed-one/processing.py",
                "commit_sha": "2222222222222222222222222222222222222222",
            },
        },
    },
}


def available_stages():
    return sorted(STAGE_SOURCES.keys())


def run_prod_stage(stage_name):
    stage_record = STAGE_SOURCES[stage_name]["prod"]
    return execute_stage("prod", stage_name, stage_record)


def run_dev_stage(stage_name):
    stage_record = STAGE_SOURCES[stage_name]["dev"]
    return execute_stage("dev", stage_name, stage_record)


def run_both(stage_name):
    try:
        run_prod_stage(stage_name)
    except Exception as exc:
        print(f"prod {stage_name} failed: {exc}")
        traceback.print_exc()

    try:
        run_dev_stage(stage_name)
    except Exception as exc:
        print(f"dev {stage_name} failed: {exc}")
        traceback.print_exc()


if __name__ == "__main__":
    print("Generated script loaded.")
    print("Available stages:", ", ".join(available_stages()))
    print('Call run_both("<stage_name>") to execute prod then dev for a stage.')
