"""
Generated by acem-script-builder.

Project: models
Target: acem-feed-one
Prod branch: main @ 1111111111111111111111111111111111111111
Dev branch: dev @ 2222222222222222222222222222222222222222

This file is generated. Do not edit by hand.
"""

import traceback


def log_event(stage, wrapper_name, message):
    print(f"[{stage}] {wrapper_name}: {message}")


def output_prod(wrapper_name, status, payload=None):
    print(f"[PROD OUTPUT] {wrapper_name} status={status}")
    if payload is not None:
        print(payload)


def output_test(wrapper_name, status, payload=None):
    print(f"[DEV OUTPUT] {wrapper_name} status={status}")
    if payload is not None:
        print(payload)


def execute_wrapper(stage, wrapper_name, fn):
    try:
        payload = fn()
        if stage == "prod":
            output_prod(wrapper_name, "success", payload)
        else:
            output_test(wrapper_name, "success", payload)
        return payload
    except Exception as exc:
        log_event(stage, wrapper_name, f"failed with {exc}")
        traceback.print_exc()
        return None


def run_prod_acem_feed_one_models_feeds_acem_feed_one_fetcher_py_1a2b3c4d():
    metadata = dict(
        source_project="models",
        source_branch="main",
        source_target="acem-feed-one",
        original_file="Models/Feeds/acem-feed-one/fetcher.py",
        commit_sha="1111111111111111111111111111111111111111",
    )
    log_event("prod", "run_prod_acem_feed_one_models_feeds_acem_feed_one_fetcher_py_1a2b3c4d", f"starting {metadata}")
    namespace = {
        "__name__": "__generated_wrapper__",
        "__file__": metadata["original_file"],
        "WRAPPER_METADATA": metadata,
    }
    exec(
        compile(
            "def fetch():\n    return {'source': 'prod'}\n",
            metadata["original_file"],
            "exec",
        ),
        namespace,
        namespace,
    )
    return {"metadata": metadata, "symbols": sorted(namespace.keys())}


def run_dev_acem_feed_one_models_feeds_acem_feed_one_fetcher_py_1a2b3c4d():
    metadata = dict(
        source_project="models",
        source_branch="dev",
        source_target="acem-feed-one",
        original_file="Models/Feeds/acem-feed-one/fetcher.py",
        commit_sha="2222222222222222222222222222222222222222",
    )
    log_event("dev", "run_dev_acem_feed_one_models_feeds_acem_feed_one_fetcher_py_1a2b3c4d", f"starting {metadata}")
    namespace = {
        "__name__": "__generated_wrapper__",
        "__file__": metadata["original_file"],
        "WRAPPER_METADATA": metadata,
    }
    exec(
        compile(
            "def fetch():\n    return {'source': 'dev'}\n",
            metadata["original_file"],
            "exec",
        ),
        namespace,
        namespace,
    )
    return {"metadata": metadata, "symbols": sorted(namespace.keys())}


def run_prod():
    wrappers = [run_prod_acem_feed_one_models_feeds_acem_feed_one_fetcher_py_1a2b3c4d]
    results = []
    for wrapper in wrappers:
        results.append(execute_wrapper("prod", wrapper.__name__, wrapper))
    return results


def run_dev():
    wrappers = [run_dev_acem_feed_one_models_feeds_acem_feed_one_fetcher_py_1a2b3c4d]
    results = []
    for wrapper in wrappers:
        results.append(execute_wrapper("dev", wrapper.__name__, wrapper))
    return results


if __name__ == "__main__":
    try:
        run_prod()
    except Exception as exc:
        print(f"prod dispatcher failed: {exc}")
        traceback.print_exc()

    try:
        run_dev()
    except Exception as exc:
        print(f"dev dispatcher failed: {exc}")
        traceback.print_exc()
