"""Generate deployable combined scripts.

The generated artifact is a stage-dispatch container. It embeds the `main`
and `dev` source text for each known stage and exposes runtime dispatch
helpers such as `run_both("processing")`.
"""

from __future__ import annotations

from pathlib import PurePosixPath

from models.config_models import BuildTarget, SourceFile


HEADER_TEMPLATE = '''"""
Generated by acem-script-builder.

Project: {project_name}
Target: {target_name}
Prod branch: main @ {main_sha}
Dev branch: dev @ {dev_sha}

This file is generated. Do not edit by hand.
"""
'''


def generate_combined_script(target: BuildTarget) -> str:
    """Render one combined artifact for a target."""

    main_sha = target.prod_files[0].commit_sha if target.prod_files else "missing"
    dev_sha = target.dev_files[0].commit_sha if target.dev_files else "missing"
    parts = [
        HEADER_TEMPLATE.format(
            project_name=target.project_name,
            target_name=target.target_name,
            main_sha=main_sha,
            dev_sha=dev_sha,
        ).strip(),
        _render_runtime_helpers(),
        _render_stage_order(target),
    ]

    parts.append(_render_stage_sources(target))
    parts.append(_render_dispatchers())
    parts.append(_render_main_block())
    return "\n\n\n".join(parts) + "\n"


def _render_runtime_helpers() -> str:
    return """import traceback


def log_event(stage, scope, message):
    print(f"[{stage}] {scope}: {message}")


def output_prod(stage_name, status, payload=None):
    print(f"[PROD OUTPUT] {stage_name} status={status}")
    if payload is not None:
        print(payload)


def output_test(stage_name, status, payload=None):
    print(f"[DEV OUTPUT] {stage_name} status={status}")
    if payload is not None:
        print(payload)


def _build_namespace(metadata):
    return {
        "__name__": "__generated_stage__",
        "__file__": metadata["original_file"],
        "STAGE_METADATA": metadata,
        "output_prod": output_prod,
        "output_test": output_test,
        "log_event": log_event,
    }


def execute_stage(stage_mode, stage_name, stage_record):
    metadata = stage_record["metadata"]
    source = stage_record["source"]
    namespace = _build_namespace(metadata)
    try:
        log_event(stage_mode, stage_name, f"starting {metadata}")
        exec(
            compile(
                source,
                metadata["original_file"],
                "exec",
            ),
            namespace,
            namespace,
        )
        payload = {
            "metadata": metadata,
            "symbols": sorted(namespace.keys()),
        }
        if stage_mode == "prod":
            output_prod(stage_name, "success", payload)
        else:
            output_test(stage_name, "success", payload)
        return payload
    except Exception as exc:
        log_event(stage_mode, stage_name, f"failed with {exc}")
        traceback.print_exc()
        return None
"""


def _render_stage_sources(target: BuildTarget) -> str:
    stage_records: dict[str, dict[str, str]] = {}

    for source_file in target.prod_files:
        stage_name = _stage_name(source_file.file_path)
        stage_records.setdefault(stage_name, {})["prod"] = _stage_record(source_file)

    for source_file in target.dev_files:
        stage_name = _stage_name(source_file.file_path)
        stage_records.setdefault(stage_name, {})["dev"] = _stage_record(source_file)

    lines = ["STAGE_SOURCES = {"]
    ordered_stage_names = _ordered_stage_names(target, stage_records)
    for stage_name in ordered_stage_names:
        lines.append(f"    {stage_name!r}: {{")
        if "prod" in stage_records[stage_name]:
            lines.append(f"        'prod': {stage_records[stage_name]['prod']},")
        if "dev" in stage_records[stage_name]:
            lines.append(f"        'dev': {stage_records[stage_name]['dev']},")
        lines.append("    },")
    lines.append("}")
    return "\n".join(lines)


def _stage_record(source_file: SourceFile) -> str:
    return (
        "{"
        f"'source': {source_file.content!r}, "
        "'metadata': {"
        f"'source_project': {source_file.project_name!r}, "
        f"'source_branch': {source_file.branch!r}, "
        f"'source_target': {source_file.target_name!r}, "
        f"'original_file': {source_file.file_path!r}, "
        f"'commit_sha': {source_file.commit_sha!r}"
        "}"
        "}"
    )


def _render_stage_order(target: BuildTarget) -> str:
    stage_names = [_stage_name(file_name) for file_name in target.stage_order]
    return f"STAGE_ORDER = {stage_names!r}"


def _render_dispatchers() -> str:
    return """def available_stages():
    ordered = [stage_name for stage_name in STAGE_ORDER if stage_name in STAGE_SOURCES]
    extras = [stage_name for stage_name in sorted(STAGE_SOURCES.keys()) if stage_name not in ordered]
    return ordered + extras


def run_prod_stage(stage_name):
    stage_record = STAGE_SOURCES[stage_name]["prod"]
    return execute_stage("prod", stage_name, stage_record)


def run_dev_stage(stage_name):
    stage_record = STAGE_SOURCES[stage_name]["dev"]
    return execute_stage("dev", stage_name, stage_record)


def run_both(stage_name):
    try:
        run_prod_stage(stage_name)
    except Exception as exc:
        print(f"prod {stage_name} failed: {exc}")
        traceback.print_exc()

    try:
        run_dev_stage(stage_name)
    except Exception as exc:
        print(f"dev {stage_name} failed: {exc}")
        traceback.print_exc()
"""


def _render_main_block() -> str:
    return """if __name__ == "__main__":
    print("Generated script loaded.")
    print("Available stages:", ", ".join(available_stages()))
    print('Call run_both("<stage_name>") to execute prod then dev for a stage.')
"""


def _stage_name(file_path: str) -> str:
    return PurePosixPath(file_path).stem


def _ordered_stage_names(target: BuildTarget, stage_records: dict[str, dict[str, str]]) -> list[str]:
    ordered = [_stage_name(file_name) for file_name in target.stage_order if _stage_name(file_name) in stage_records]
    extras = [stage_name for stage_name in sorted(stage_records) if stage_name not in ordered]
    return ordered + extras
