"""Generate deployable combined scripts.

v1 intentionally preserves source file contents and executes each file in
its own wrapper. That keeps generation straightforward and deterministic,
but it also means intra-project imports are not rewritten or bundled.
"""

from __future__ import annotations

import hashlib

from models.config_models import BuildTarget, SourceFile


HEADER_TEMPLATE = '''"""
Generated by acem-script-builder.

Project: {project_name}
Target: {target_name}
Prod branch: main @ {main_sha}
Dev branch: dev @ {dev_sha}

This file is generated. Do not edit by hand.
"""
'''


def generate_combined_script(target: BuildTarget) -> str:
    """Render one combined artifact for a target."""

    main_sha = target.prod_files[0].commit_sha if target.prod_files else "missing"
    dev_sha = target.dev_files[0].commit_sha if target.dev_files else "missing"
    parts = [
        HEADER_TEMPLATE.format(
            project_name=target.project_name,
            target_name=target.target_name,
            main_sha=main_sha,
            dev_sha=dev_sha,
        ).strip(),
        _render_runtime_helpers(),
    ]

    for source_file in target.prod_files:
        parts.append(_render_wrapper(source_file, target.target_name, "prod"))
    for source_file in target.dev_files:
        parts.append(_render_wrapper(source_file, target.target_name, "dev"))

    parts.append(_render_dispatcher("prod", target.prod_files, target.target_name))
    parts.append(_render_dispatcher("dev", target.dev_files, target.target_name))
    parts.append(_render_main_block())
    return "\n\n\n".join(parts) + "\n"


def _render_runtime_helpers() -> str:
    return """import traceback


def log_event(stage, wrapper_name, message):
    print(f"[{stage}] {wrapper_name}: {message}")


def output_prod(wrapper_name, status, payload=None):
    print(f"[PROD OUTPUT] {wrapper_name} status={status}")
    if payload is not None:
        print(payload)


def output_test(wrapper_name, status, payload=None):
    print(f"[DEV OUTPUT] {wrapper_name} status={status}")
    if payload is not None:
        print(payload)


def execute_wrapper(stage, wrapper_name, fn):
    try:
        payload = fn()
        if stage == "prod":
            output_prod(wrapper_name, "success", payload)
        else:
            output_test(wrapper_name, "success", payload)
        return payload
    except Exception as exc:
        log_event(stage, wrapper_name, f"failed with {exc}")
        traceback.print_exc()
        return None
"""


def _render_wrapper(source_file: SourceFile, target_name: str, stage: str) -> str:
    function_name = _wrapper_name(stage, target_name, source_file.file_path)
    metadata = (
        f"source_project={source_file.project_name!r}, "
        f"source_branch={source_file.branch!r}, "
        f"source_target={source_file.target_name!r}, "
        f"original_file={source_file.file_path!r}, "
        f"commit_sha={source_file.commit_sha!r}"
    )
    return f"""def {function_name}():
    metadata = dict({metadata})
    log_event("{stage}", "{function_name}", f"starting {{metadata}}")
    namespace = {{
        "__name__": "__generated_wrapper__",
        "__file__": metadata["original_file"],
        "WRAPPER_METADATA": metadata,
    }}
    exec(
        compile(
            {source_file.content!r},
            metadata["original_file"],
            "exec",
        ),
        namespace,
        namespace,
    )
    return {{
        "metadata": metadata,
        "symbols": sorted(namespace.keys()),
    }}"""


def _render_dispatcher(stage: str, files: list[SourceFile], target_name: str) -> str:
    wrapper_names = [_wrapper_name(stage, target_name, source_file.file_path) for source_file in files]
    return f"""def run_{stage}():
    wrappers = [{", ".join(wrapper_names)}]
    results = []
    for wrapper in wrappers:
        results.append(execute_wrapper("{stage}", wrapper.__name__, wrapper))
    return results"""


def _render_main_block() -> str:
    return """if __name__ == "__main__":
    try:
        run_prod()
    except Exception as exc:
        print(f"prod dispatcher failed: {exc}")
        traceback.print_exc()

    try:
        run_dev()
    except Exception as exc:
        print(f"dev dispatcher failed: {exc}")
        traceback.print_exc()
"""


def _wrapper_name(stage: str, target_name: str, file_path: str) -> str:
    clean_target = _slug(target_name)
    clean_file = _slug(file_path.replace("/", "_"))
    digest = hashlib.sha1(file_path.encode("utf-8")).hexdigest()[:8]
    return f"run_{stage}_{clean_target}_{clean_file}_{digest}"


def _slug(value: str) -> str:
    allowed = []
    for char in value.lower():
        if char.isalnum():
            allowed.append(char)
        else:
            allowed.append("_")
    collapsed = "".join(allowed).strip("_")
    while "__" in collapsed:
        collapsed = collapsed.replace("__", "_")
    return collapsed or "target"
